[package]
name = "nazgul"
description = "A library that implements various ring signature schemes"
readme = "README.md"
license = "MIT"
version = "0.1.0"
authors = ["Edwin Jose Palathinkal <edwinhere@gmail.com>"]
edition = "2018"
keywords = ["cryptography", "crypto", "ristretto", "ristretto255", "monero"]
categories = ["no-std", "cryptography::cryptocurrencies", "cryptography", "wasm"]
repository = "https://github.com/edwinhere/nazgul"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "2"
digest = "0.8.1"
rand_core = "0.5.1"

[dev-dependencies]
sha2 = "0.8.1"
sha3 = "0.8.2"
blake2 = "0.8.1"
rand = "0.7.3"
